version: '3.8'


services:
  mongo-db:
    image: mongo:6.0.6
    container_name: mongo-db-1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - databases_volume:/data/db
    ports:
      - 27017:27017

  postgres-db:
    image: postgres:16.4
    container_name: postgres-db-1
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - databases_volume:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
volumes:
    databases_volume:
        external: true

